name: Publish package to PIP

on: [push]
if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # Only on tagged commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Checkout the project
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.13'

        - name: Build dev env
          run: docker build --tag local --file Dockerfile --target prod .

        - name: Build python package
          run: docker run local poetry build

        - name: Publish a Python distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}