name: Publish package to PIP

on:
  release:
    types: [published]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Checkout the project
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Build dev env
        run: docker build --tag local --file Dockerfile --target dev .

      - name: Lint
        run: docker run local flake8

      - name: Start testing environment
        run: docker run -e SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }} local pytest


  publish:
    needs: test
    environment:
      name: pypi-publish
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Checkout the project
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.13'

        - name: Build dev env
          run: docker build --tag local --file Dockerfile --target prod .

        - name: Publish a Python distribution to PyPI
          run: |
            docker run local /bin/bash -c \
              "poetry version ${{ github.ref_name }} && 
              poetry publish \
                --build \
                --username ${{secrets.PYPI_USERNAME}} \
                --password ${{secrets.PYPI_PASSWORD}}"