name: Publish package to PIP

on:
# Just for testing
  push:
    branches:
      - "fix/publish-workflow"
  release:
    types: [published]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Checkout the project
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Build dev env
        run: docker build --tag local --file Dockerfile --target dev .

      - name: Lint
        run: docker run local flake8

      - name: Start testing environment
        run: docker run -e SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }} local pytest


  publish:
    needs: test
    environment:
      name: pypi-publish
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Checkout the project
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.13'

        - name: Build dev env
          run: docker build --tag local --file Dockerfile --target prod .

        - name: Build python package
          run: docker run local poetry build

        # Just for testing
        # docker run local poetry version $(git describe --tags --abbrev=0)
        - name: Publish a Python distribution to PyPI
          run: |
            docker run local poetry version 0.3.3
            docker run local poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN}}
            docker run local poetry build
            docker run local poetry publish